[book]
title = "C#程序员的Rust"
authors = ["Rust Training Team"]
language = "zh-CN"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/rust-systems-training/rust-training"
default-theme = "light"
preferred-dark-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = true
line-numbers = true
