[book]
title = "Rust工程实践"
authors = ["Rust Training Team"]
language = "zh-CN"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/rust-systems-training/rust-training"
default-theme = "light"
preferred-dark-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = true
line-numbers = true

# [output.epub]
# curly-quotes = true
# footnote-backrefs = true
# no-section-label = false
# use-default-css = true
# additional-css = ["src/epub.css"]
